# Generated by Django 4.2.25 on 2025-11-01 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreference',
            name='preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchanthotproduct',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchanthotproduct',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='administor',
            table='administors',
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attributes',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='customerpreference',
            table='customer_preferences',
        ),
        migrations.AlterModelTable(
            name='merchanthotproduct',
            table='merchant_hot_products',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productuserportrait',
            table='product_user_portraits',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userdialogue',
            table='user_dialogues',
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
    ]
